# Generated by Django 2.0.5 on 2019-03-15 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQ',
            new_name='Qna',
        ),
    ]
