# Generated by Django 2.0 on 2019-03-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0003_auto_20190319_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Qna',
        ),
    ]
