# Generated by Django 2.0.5 on 2019-03-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletinboard', '0002_auto_20190315_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletinboard',
            name='author',
        ),
        migrations.RemoveField(
            model_name='bulletinboard',
            name='hits',
        ),
        migrations.AddField(
            model_name='bulletinboard',
            name='writer',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
