# Generated by Django 2.0.5 on 2019-03-15 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletinboard', '0004_auto_20190315_2202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
