# Generated by Django 2.0 on 2019-03-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='roomNum',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
