# Generated by Django 2.0 on 2019-03-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_information_roomnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='logo',
            field=models.ImageField(default='', upload_to='information/'),
            preserve_default=False,
        ),
    ]
