# Generated by Django 2.0 on 2019-03-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_information_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='image1',
            field=models.ImageField(default='', upload_to='information/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='image2',
            field=models.ImageField(default='', upload_to='information/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='image3',
            field=models.ImageField(default='', upload_to='information/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='image4',
            field=models.ImageField(default='', upload_to='information/'),
            preserve_default=False,
        ),
    ]
