# Generated by Django 2.0 on 2019-03-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_auto_20190313_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='map',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
