# Generated by Django 2.0 on 2019-03-14 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_information_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='image4',
            field=models.ImageField(null=True, upload_to='information/'),
        ),
        migrations.AlterField(
            model_name='information',
            name='map',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
