# Generated by Django 2.0 on 2019-03-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0006_auto_20190314_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='information/'),
        ),
        migrations.AlterField(
            model_name='information',
            name='map',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
