# Generated by Django 2.0 on 2019-03-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0008_auto_20190314_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='elementary',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='middleHigh',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
