# Generated by Django 2.0 on 2019-03-08 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('name', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=11)),
                ('numPeople', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('numPeople', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('genre', models.CharField(max_length=20)),
                ('horror', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.Theme'),
        ),
    ]
