# Generated by Django 2.0 on 2019-03-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='image',
            field=models.ImageField(default='', upload_to='theme/'),
            preserve_default=False,
        ),
    ]
