# Generated by Django 2.0 on 2019-03-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0004_auto_20190311_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='dateTime',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default='2019-03-11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.TimeField(default='12:00'),
            preserve_default=False,
        ),
    ]
