# Generated by Django 2.0 on 2019-03-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0006_auto_20190312_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='activity',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
