# Generated by Django 2.0 on 2019-03-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0008_auto_20190314_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='activity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='genre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='horror',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='numPeople',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
