# Generated by Django 2.0 on 2019-03-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0009_auto_20190314_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='mobile_summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
