# Generated by Django 2.0 on 2019-03-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0010_theme_mobile_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='time11',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='time12',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
