# Generated by Django 2.0 on 2019-03-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0011_auto_20190321_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='depositWay',
            field=models.CharField(blank=True, choices=[('현장결제', '현장결제'), ('무통장선결제', '무통장선결제')], max_length=20, null=True),
        ),
    ]
