# Generated by Django 2.0 on 2019-03-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0012_auto_20190323_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='numPeople',
            field=models.CharField(blank=True, choices=[('1명', '1명'), ('2명', '2명'), ('3명', '3명'), ('4명', '4명'), ('5명', '5명'), ('6명', '6명')], max_length=20, null=True),
        ),
    ]
