# Generated by Django 2.0 on 2019-04-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0013_auto_20190323_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='depositWay',
            field=models.CharField(choices=[('현장결제', '현장결제'), ('무통장선결제', '무통장선결제')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='numPeople',
            field=models.CharField(choices=[('1명', '1명'), ('2명', '2명'), ('3명', '3명'), ('4명', '4명'), ('5명', '5명'), ('6명', '6명')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
